//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDevSistemas2023.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoDevSistemas2023.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir Aplicação.
        /// </summary>
        internal static string abrirAplicaçãoToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("abrirAplicaçãoToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string BAIRRO_Text1 {
            get {
                return ResourceManager.GetString("BAIRRO.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a bairro.
        /// </summary>
        internal static string BAIRROFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("BAIRROFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string buttonConfiguracao_Text1 {
            get {
                return ResourceManager.GetString("buttonConfiguracao.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditar_Text1 {
            get {
                return ResourceManager.GetString("buttonEditar.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluir_Text1 {
            get {
                return ResourceManager.GetString("buttonExcluir.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFechar_Text1 {
            get {
                return ResourceManager.GetString("buttonFechar.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvar_Text1 {
            get {
                return ResourceManager.GetString("buttonSalvar.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarIdioma_Text1 {
            get {
                return ResourceManager.GetString("buttonSalvarIdioma.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Do Endereço.
        /// </summary>
        internal static string Cadastrodeendereçodocliente_Text1 {
            get {
                return ResourceManager.GetString("Cadastrodeendereçodocliente.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Do Cliente.
        /// </summary>
        internal static string CadastroDoCliente_Text1 {
            get {
                return ResourceManager.GetString("CadastroDoCliente.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Do Funcionário.
        /// </summary>
        internal static string CADASTROFUNC_Text1 {
            get {
                return ResourceManager.GetString("CADASTROFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de ingredientes.
        /// </summary>
        internal static string CadastroING_Text1 {
            get {
                return ResourceManager.GetString("CadastroING.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produtos.
        /// </summary>
        internal static string CadastroProdutos_Text1 {
            get {
                return ResourceManager.GetString("CadastroProdutos.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro dos Sabores.
        /// </summary>
        internal static string CadastroSABORES_Text1 {
            get {
                return ResourceManager.GetString("CadastroSABORES.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de valores.
        /// </summary>
        internal static string CadastroVal_Text1 {
            get {
                return ResourceManager.GetString("CadastroVal.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Valores.
        /// </summary>
        internal static string CadastroValores_Text1 {
            get {
                return ResourceManager.GetString("CadastroValores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string CADCAT_Text1 {
            get {
                return ResourceManager.GetString("CADCAT.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string CADid_Text1 {
            get {
                return ResourceManager.GetString("CADid.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Dos Produtos.
        /// </summary>
        internal static string CADPROD_Text1 {
            get {
                return ResourceManager.GetString("CADPROD.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string CADTAM_Text1 {
            get {
                return ResourceManager.GetString("CADTAM.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor adcional da borda.
        /// </summary>
        internal static string CADVAB_Text1 {
            get {
                return ResourceManager.GetString("CADVAB.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string CADVAL_Text1 {
            get {
                return ResourceManager.GetString("CADVAL.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria dos sabores.
        /// </summary>
        internal static string categoriasabores_Text1 {
            get {
                return ResourceManager.GetString("categoriasabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione o Idioma.
        /// </summary>
        internal static string CBidiomaregiao_Text1 {
            get {
                return ResourceManager.GetString("CBidiomaregiao.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        internal static string CEP_Text1 {
            get {
                return ResourceManager.GetString("CEP.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP funcionario.
        /// </summary>
        internal static string CEPFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("CEPFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reiniciar programa para estabelecer a linguagem escolhida.
        /// </summary>
        internal static string checkBoxidiomaregiao_Text1 {
            get {
                return ResourceManager.GetString("checkBoxidiomaregiao.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        internal static string CIDADE_Text1 {
            get {
                return ResourceManager.GetString("CIDADE.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a cidade.
        /// </summary>
        internal static string CIDADEFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("CIDADEFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string CLIENTES1_Text1 {
            get {
                return ResourceManager.GetString("CLIENTES1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente.
        /// </summary>
        internal static string clienteToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("clienteToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carteira de motorista do Funcionario.
        /// </summary>
        internal static string CMFUNC_Text1 {
            get {
                return ResourceManager.GetString("CMFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string COMPLEMENTO_Text1 {
            get {
                return ResourceManager.GetString("COMPLEMENTO.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a complemento da casa.
        /// </summary>
        internal static string COMPLEMENTOFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("COMPLEMENTOFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuração.
        /// </summary>
        internal static string configuraçãoToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("configuraçãoToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string CPF_Text1 {
            get {
                return ResourceManager.GetString("CPF.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf Do Funcionário.
        /// </summary>
        internal static string CPFFUNC_Text1 {
            get {
                return ResourceManager.GetString("CPFFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string EMAIL_Text1 {
            get {
                return ResourceManager.GetString("EMAIL.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a email do funcionario.
        /// </summary>
        internal static string EMAILFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("EMAILFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encerrar.
        /// </summary>
        internal static string encerrarToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("encerrarToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a foto.
        /// </summary>
        internal static string fotosabores_Text1 {
            get {
                return ResourceManager.GetString("fotosabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionarios.
        /// </summary>
        internal static string FUNCIONÁRIOS1_Text1 {
            get {
                return ResourceManager.GetString("FUNCIONÁRIOS1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string funcionárioToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("funcionárioToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string ID_Text1 {
            get {
                return ResourceManager.GetString("ID.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID endereço.
        /// </summary>
        internal static string IDENDEREÇO_Text1 {
            get {
                return ResourceManager.GetString("IDENDEREÇO.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Do Funcionário.
        /// </summary>
        internal static string IDFUNC_Text1 {
            get {
                return ResourceManager.GetString("IDFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID funcionario.
        /// </summary>
        internal static string IDFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("IDFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID dos ingredientes.
        /// </summary>
        internal static string IDING_Text1 {
            get {
                return ResourceManager.GetString("IDING.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string idiomaregiao_Text1 {
            get {
                return ResourceManager.GetString("idiomaregiao.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Produtos.
        /// </summary>
        internal static string IDPROD_Text1 {
            get {
                return ResourceManager.GetString("IDPROD.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string IDsabores_Text1 {
            get {
                return ResourceManager.GetString("IDsabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string INGREDIENTES1_Text1 {
            get {
                return ResourceManager.GetString("INGREDIENTES1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ingredientes.
        /// </summary>
        internal static string ingredientessabores_Text1 {
            get {
                return ResourceManager.GetString("ingredientessabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingrediente.
        /// </summary>
        internal static string ingredienteToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("ingredienteToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio.
        /// </summary>
        internal static string inicioToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("inicioToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string labelidiomaregiao_Text1 {
            get {
                return ResourceManager.GetString("labelidiomaregiao.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro funcionario.
        /// </summary>
        internal static string LOGFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("LOGFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        internal static string LOGRADOURO_Text1 {
            get {
                return ResourceManager.GetString("LOGRADOURO.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula Do Funcionário.
        /// </summary>
        internal static string MATRICULAFUNC_Text1 {
            get {
                return ResourceManager.GetString("MATRICULAFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ML.
        /// </summary>
        internal static string MLPROd_Text1 {
            get {
                return ResourceManager.GetString("MLPROd.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string Nome_Text1 {
            get {
                return ResourceManager.GetString("Nome.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Do Funcionário.
        /// </summary>
        internal static string NOMEFUNC_Text1 {
            get {
                return ResourceManager.GetString("NOMEFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome dos ingredientes.
        /// </summary>
        internal static string NomeING_Text1 {
            get {
                return ResourceManager.GetString("NomeING.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome dos produtos.
        /// </summary>
        internal static string NomePROD_Text1 {
            get {
                return ResourceManager.GetString("NomePROD.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a nome dos sabores.
        /// </summary>
        internal static string nomesabores_Text1 {
            get {
                return ResourceManager.GetString("nomesabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero.
        /// </summary>
        internal static string NUMERO_Text1 {
            get {
                return ResourceManager.GetString("NUMERO.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a numero da casa.
        /// </summary>
        internal static string NUMEROFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("NUMEROFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação.
        /// </summary>
        internal static string OBSERVAÇAOFUNC_Text1 {
            get {
                return ResourceManager.GetString("OBSERVAÇAOFUNC.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        internal static string PAÍS_Text1 {
            get {
                return ResourceManager.GetString("PAÍS.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a país.
        /// </summary>
        internal static string PAÍSFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("PAÍSFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza {
            get {
                object obj = ResourceManager.GetObject("pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pizzaria do zé.
        /// </summary>
        internal static string PIZZARIADOZE_Text1 {
            get {
                return ResourceManager.GetString("PIZZARIADOZE.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string produtosToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de endereço do funcionário.
        /// </summary>
        internal static string REGENDDOFUN_Text1 {
            get {
                return ResourceManager.GetString("REGENDDOFUN.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-senha.
        /// </summary>
        internal static string RESENHA_Text1 {
            get {
                return ResourceManager.GetString("RESENHA.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string SABORES1_Text1 {
            get {
                return ResourceManager.GetString("SABORES1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string saboresToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("saboresToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string sairToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("sairToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string SENHA_Text1 {
            get {
                return ResourceManager.GetString("SENHA.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string sobreToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("sobreToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string TELEFONE_Text1 {
            get {
                return ResourceManager.GetString("TELEFONE.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a telefone do funcionario.
        /// </summary>
        internal static string TELEFONEFUNCEND_Text1 {
            get {
                return ResourceManager.GetString("TELEFONEFUNCEND.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo dos Produtos.
        /// </summary>
        internal static string TIPOPROD_Text1 {
            get {
                return ResourceManager.GetString("TIPOPROD.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a tipo dos sabores.
        /// </summary>
        internal static string tiposabores_Text1 {
            get {
                return ResourceManager.GetString("tiposabores.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        internal static string UF_Text1 {
            get {
                return ResourceManager.GetString("UF.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a estado.
        /// </summary>
        internal static string UFENDFUN_Text1 {
            get {
                return ResourceManager.GetString("UFENDFUN.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade.
        /// </summary>
        internal static string VALIDADE_Text1 {
            get {
                return ResourceManager.GetString("VALIDADE.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores.
        /// </summary>
        internal static string valoresToolStripMenuItem_Text1 {
            get {
                return ResourceManager.GetString("valoresToolStripMenuItem.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string VALorPROD_Text1 {
            get {
                return ResourceManager.GetString("VALorPROD.Text1", resourceCulture);
            }
        }
    }
}
